# Generated by Django 3.2 on 2022-04-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='treatment',
        ),
    ]
