# Generated by Django 3.2 on 2022-04-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0005_rename_booking_date_time_booking_booking_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='time',
        ),
    ]
